### ISSUE TITLE
Mitigation to disable DCOM

### ISSUE THREAD

**Issue by CalvinKrist** [ION28/BLUESPAWN#132]
REG ADD HKEY_LOCAL_MACHINE\Software\Microsoft\OLE /v EnableDCOM /t REG_SZ /d N /F

**Comment by ION28** [comment]
May break functionality in many environments if they rely on remote management. Will close this for now.

**Comment by ION28** [comment]
https://attack.mitre.org/techniques/T1175/

**Comment by ION28** [comment]
Closed by accident

**Comment by ION28** [comment]
https://support.microsoft.com/en-us/help/825750/how-to-disable-dcom-support-in-windows

**Comment by ION28** [comment]
I'm really hesitant to implement this before we have levels of security within Mitigations as this should only be applied in extreme cases
