### ISSUE TITLE
Add mitigations for enabling log files

### ISSUE THREAD

**Issue by CalvinKrist** [ION28/BLUESPAWN#134]
Remaining on this issue
- [x] Enable the following logs (based on https://github.com/nsacyber/Event-Forwarding-Guidance/blob/master/Events/README.md)
  - [x] Certificate logs - provider: Microsoft-Windows-CertificateServicesClientLifecycle-System channel: Microsoft-Windows-CertificateServicesClientLifecycle-System/Operational
  - [x] Bits logs - provider: Microsoft-Windows-Bits-Client channel: Microsoft-Windows-Bits-Client/Operational
  - [x] Account Usage - provider: Microsoft-Windows-Security-Auditing channel: Security
  - [x] Applocker ( Microsoft-Windows-AppLocker/EXE and DLL and Microsoft-Windows-AppLocker/MSI and Script
  - [x] Event log - provider: Microsoft-Windows-Eventlog channel: Security
  - [x] Powershell - provider: Microsoft-Windows-Powershell channel: Microsoft-Windows-Powershell/Operational
  - [x] Task Scheduler - provider: Microsoft-Windows-TaskScheduler channel: Microsoft-Windows-TaskScheduler/Operational
  - [x] Windows Defender - provider: Microsoft-Windows-Windows Defender channel: Microsoft-Windows-Windows Defender/Operational
  - [x] Windows Firewall - provider: Microsoft-Windows-Windows Firewall With Advanced Security channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
  - [x] Sysmon - provider: Microsoft-Windows-Sysmon channel: Microsoft-Windows-Sysmon/Operational
- [ ] Add s/o on README to NSA Cybersecurity's Event Forwarding Guidance Repository https://github.com/nsacyber/Event-Forwarding-Guidance

**Comment by ION28** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/WinEvt/ne-winevt-evt_channel_config_property_id

https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtsetchannelconfigproperty

```c++
EVT_HANDLE hChannel = NULL;
	DWORD status = ERROR_SUCCESS;
	EVT_VARIANT ChannelProperty;
	DWORD dwBufferSize = sizeof(EVT_VARIANT);
	DWORD dwBufferUsed = 0;
	hChannel = EvtOpenChannelConfig(NULL, L"Microsoft-Windows-TaskScheduler/Operational", 0);
	if (NULL == hChannel)
	{
		wprintf(L"EvtOpenChannelConfig failed with %lu.\n", GetLastError());
	}
	RtlZeroMemory(&ChannelProperty, dwBufferSize);

	ChannelProperty.Type = EvtVarTypeBoolean;
	ChannelProperty.BooleanVal = TRUE;
	if (!EvtSetChannelConfigProperty(hChannel, EvtChannelConfigEnabled, 0, &ChannelProperty))
	{
		wprintf(L"EvtSetChannelConfigProperty for Enabled property failed with %lu\n", GetLastError());
	}
	if (!EvtSaveChannelConfig(hChannel, 0))
	{
		wprintf(L"EvtSaveChannelConfig failed with %lu\n", GetLastError());
	}
	wprintf(L"Channel properties updated.\n");
```

**Comment by ION28** [comment]
Microsoft-Windows-CertificateServicesClientLifecycle-System

**Comment by ION28** [comment]
Look through this, enable certain logs as needed, and make issues for most exciting logs (including sysmon detections) https://github.com/nsacyber/Event-Forwarding-Guidance/blob/master/Events/README.md

**Comment by ION28** [comment]
http://smallvoid.com/article/winnt-services-regedit.html (service start types)

**Comment by ION28** [comment]
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Sysmon64`

and `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog`

**Comment by ION28** [comment]
Remaining on this issue
- [ ] Enable the following logs
  - [ ] Certificate logs - provider: Microsoft-Windows-CertificateServicesClientLifecycle-System channel: Microsoft-Windows-CertificateServicesClientLifecycle-System/Operational
  - [ ] Bits logs - provider: Microsoft-Windows-Bits-Client channel: Microsoft-Windows-Bits-Client/Operational
  - [ ] Account Usage - provider: Microsoft-Windows-Security-Auditing channel: Security
  - [ ] Applocker ( Microsoft-Windows-AppLocker/EXE and DLL and Microsoft-Windows-AppLocker/MSI and Script
  - [ ] Event log - provider: Microsoft-Windows-Eventlog channel: Security
  - [ ] Powershell - provider: Microsoft-Windows-Powershell channel: Microsoft-Windows-Powershell/Operational
  - [ ] Task Scheduler - provider: Microsoft-Windows-TaskScheduler channel: Microsoft-Windows-TaskScheduler/Operational
  - [ ] Windows Defender - provider: Microsoft-Windows-Windows Defender channel: Microsoft-Windows-Windows Defender/Operational
  - [ ] Windows Firewall - provider: Microsoft-Windows-Windows Firewall With Advanced Security channel: Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
  - [ ] Sysmon - provider: Microsoft-Windows-Sysmon channel: Microsoft-Windows-Sysmon/Operational

**Comment by ION28** [comment]
close in #226
