### ISSUE TITLE
Hunt T1183

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#145]
Look at debuggers + GFlags: https://attack.mitre.org/techniques/T1183/

Look at Silent Exit Registry keys: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit

https://github.com/op7ic/EDR-Testing-Script/blob/master/runtests.bat#L298

**Comment by Jack-McDowell** [comment]
Done :D

**Comment by ION28** [comment]
Closed in PR #146
