### ISSUE TITLE
Implement Menu / Command Line Options

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#24]
Probably utilize this: https://github.com/jarro2783/cxxopts

**Comment by ION28** [comment]
Would appreciate input on what options are desired in here (ie, a --quiet might only report bad stuff, etc)

**Comment by ION28** [comment]
Don't need to make any of the options work, just the whole menu structure and command line flags. Issue should really focus on what are all the flags we want. Once that is done, issues need to be made to implement each of these options. Maybe design some cool ascii art for the menu too :)

**Comment by CalvinKrist** [comment]
For sure flags that deal with different levels of output, if output goes to a file or to the console, etc.

We've been envisioning this as an application that always runs in the background, so perhaps a config file would be better than a command line option. That way users can configure it just by modifying the config file, as opposed to going to scheduled tasks or wherever we've embedded ourselves and touching stuff there.

Of course, either option begs the question how do we stop malicious users from mis-configuring us . . .

**Comment by ION28** [comment]
That's a good idea, re option for a config. Kind of like sysmon in that sense. You can either given it a config or use cmd line options. 

We have 2 parts to the application. On demand scans (which it does currently) then controlling continuous monitoring mode (once the kernel driver is in place). So I imagine we'll want options to deal with both. 

We can always use some sort hashing / alerting to detect signature tampering. Regular AVs do this well - I wonder what they do?

**Comment by ION28** [comment]
This afternoon we were chatting about defcon levels. Would be a fun and useful feature

**Comment by ION28** [comment]
https://codereview.stackexchange.com/a/14315 for converting command line strings to respective enums potentially

**Comment by ION28** [comment]
first iteration implemented
