### ISSUE TITLE
Improve Code Quality

### ISSUE THREAD

**Issue by Jack-McDowell** [ION28/BLUESPAWN#308]
This one will take a log of effort. This involves - 

a) Proper commenting / naming
b) Proper usage of const and references
c) Proper C++ style casting
d) Clean up the mess that is wrappers.hpp (and functions using it)
e) Make C-style code more C++-like
f) Spacing and unified formatting

I'll take this one and write up a contribution guidelines as I do this.

**Comment by ION28** [comment]
Note to Jake: write the auto formatting thing for visual studio

**Comment by ION28** [comment]
clang-format has been added, this is a good start for now
