### ISSUE TITLE
Finally add ETW module

### ISSUE THREAD

**Issue by CalvinKrist** [ION28/BLUESPAWN#383]

**Comment by ION28** [comment]
Highly recommend looking into https://github.com/zodiacon/ProcMonXv2 

@Jack-McDowell might have some other suggested examples. I'll look for others tomorrow as well

**Comment by ION28** [comment]
Another good resource https://github.com/pathtofile/Sealighter 

Both are c++ etw projects with a security focus / connection which go beyond the krabsetw examples

**Comment by CalvinKrist** [comment]
Closed because there's a better way in the works
