### ISSUE TITLE
Client-server-add-rpc-json branch vcpkg install error

### ISSUE THREAD

**Issue by qthrones** [ION28/BLUESPAWN#393]
**branch**:client-server-add-rpc-json

`>.\vcpkg.exe install @../vcpkg_response_file.txt
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages are already installed:
    cxxopts[core]:x64-windows-static
    cxxopts[core]:x86-windows-static
    grpc[core]:x64-windows-static
    libzip[core,openssl,bzip2]:x64-windows-static
    libzip[core,openssl,bzip2]:x86-windows-static
    yara[core]:x64-windows-static
    yara[core]:x86-windows-static
The following packages will be built and installed:
  * c-ares[core]:x86-windows-static
    grpc[core]:x86-windows-static
    nlohmann-json[core]:x64-windows-static
    nlohmann-json[core]:x86-windows-static
  * protobuf[core]:x86-windows-static
  * upb[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Package yara:x64-windows-static is already installed
Package yara:x86-windows-static is already installed
Package cxxopts:x64-windows-static is already installed
Package cxxopts:x86-windows-static is already installed
Package grpc:x64-windows-static is already installed
Package libzip:x64-windows-static is already installed
Package libzip:x86-windows-static is already installed
Starting package 1/6: c-ares:x86-windows-static
Building package c-ares[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\data\projects\c\BLUESPAWN\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/data/projects/c/BLUESPAWN/vcpkg/downloads/c-ares-c-ares-9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz
-- Using source at C:/data/projects/c/BLUESPAWN/vcpkg/buildtrees/c-ares/src/c4d45be459-24e25a63ee
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package c-ares[core]:x86-windows-static... done
Installing package c-ares[core]:x86-windows-static...
Installing package c-ares[core]:x86-windows-static... done
Elapsed time for package c-ares:x86-windows-static: 9.042 min
Starting package 2/6: protobuf:x86-windows-static
Building package protobuf[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\data\projects\c\BLUESPAWN\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/data/projects/c/BLUESPAWN/vcpkg/downloads/protocolbuffers-protobuf-v3.11.3.tar.gz
-- Using source at C:/data/projects/c/BLUESPAWN/vcpkg/buildtrees/protobuf/src/v3.11.3-464ce72ac5
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Installing: C:/data/projects/c/BLUESPAWN/vcpkg/packages/protobuf_x86-windows-static/tools/protobuf/protoc.exe
-- Installing: C:/data/projects/c/BLUESPAWN/vcpkg/packages/protobuf_x86-windows-static/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package protobuf[core]:x86-windows-static... done
Installing package protobuf[core]:x86-windows-static...
Installing package protobuf[core]:x86-windows-static... done
Elapsed time for package protobuf:x86-windows-static: 7.346 min
Starting package 3/6: upb:x86-windows-static
Building package upb[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\data\projects\c\BLUESPAWN\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/data/projects/c/BLUESPAWN/vcpkg/downloads/protocolbuffers-upb-9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz
-- Using source at C:/data/projects/c/BLUESPAWN/vcpkg/buildtrees/upb/src/b291e32482-5b4f85036a
-- Configuring x86-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/data/projects/c/BLUESPAWN/vcpkg/buildtrees/upb/x86-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\data\projects\c\BLUESPAWN\vcpkg\buildtrees\upb\config-x86-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/upb/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package upb:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: upb:x86-windows-static
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.`

**Comment by ION28** [comment]
Thanks for reporting this! I will triage this and take a look today.

**Comment by qthrones** [comment]
vcpkg running using Administrator has been resolved, thank you very much for your reply.

**Comment by ION28** [comment]
@qthrones sounds good! I've also updated the Wiki page instructions to clearly specify administrative command prompt in response to your issue! https://github.com/ION28/BLUESPAWN/wiki/Setting-up-your-Development-Environment

**Comment by qthrones** [comment]
In the beginning, we have not seen a branch with a server. We plan to apply GPRC to develop our own server program. Yesterday we found out that there was a branch on the server side, and it coincided with our plan. Today we can’t wait to apply it.

**Comment by ION28** [comment]
Haha nice! Yeah based on our research grpc was definitely the way to go for client server comms given how scalable it is. I'll be honest in that it's going to be awhile to get a really usable server setup in this model (at least with the number of devs we have atm), but we're working on it and looking forward to having a server MVP
