### ISSUE TITLE
Create Processes Base

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#41]
This covers creating the .h/.cpp files and some basic functions that the corresponding HuntT####/other analysis functions will utilize. For example, there might be functions for retrieving a list of all processes running, getting all threads of a process, analyzing its code stack, or generating the checksum of a process' memory image.

Feel free to decompose into smaller issues as needed

**Comment by ION28** [comment]
https://web.archive.org/web/20170430162348/http://sysforensics.org/2014/01/know-your-windows-processes/ @jnmcd here are some ideas for some checks that can be done

**Comment by ION28** [comment]
started in 713676d727642b42db9901a4e036a5115df0ab62

**Comment by jnmcd** [comment]
in progress!

**Comment by ION28** [comment]
is this essentially done now? ie, can I/we use it in building Hunt Technique functions? If so, we can close the issue and potentially make a new one for any remaining (ex: some of that thread stuff) @Jack-McDowell

**Comment by jnmcd** [comment]
Almost. I need to swap a function around to walk the stack. If you want to check an address, that works but is untested
