### ISSUE TITLE
Create ETW Base

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#44]
creating the files needed in the vs project to do all sorts of fun stuff with ETW. This issue covers creating the .h/.cpp files as well as creating a few functions that would likely be needed by HuntT####/other analysis functions.

**Comment by ION28** [comment]
good examples: https://blogs.technet.microsoft.com/office365security/hidden-treasure-intrusion-detection-with-etw-part-1/

and 
https://ackroute.com/post/2017/08/08/sysmon-enumeration-overview/

**Comment by ION28** [comment]
https://github.com/microsoft/Windows-driver-samples/tree/41c29cb92feff490270b4ce31f67d7baddecc457/general/tracing/evntdrv

**Comment by ION28** [comment]
@CalvinKrist this will be a good item for you to work on or you can focus efforts on building some of those hunt functions for specific techniques

**Comment by ION28** [comment]
another good blog post: https://medium.com/threat-hunters-forge/threat-hunting-with-etw-events-and-helk-part-1-installing-silketw-6eb74815e4a0

**Comment by CalvinKrist** [comment]
The correct example driver: https://github.com/microsoft/Windows-driver-samples/tree/41c29cb92feff490270b4ce31f67d7baddecc457/general/tracing/SystemTraceControl
