### ISSUE TITLE
T1136 Create Account

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#51]
https://attack.mitre.org/techniques/T1136/

Security | 4720 | User Account Management | A user account was created.Attribute > Old UAC Value: Old UAC value for the user that was created (0x0)Attribute > User Account Control: Account control for the user that was createdAttribute > Account Expiration Date: Date on which the created user account expiresAttribute > Password Last Set: Last set password for the created userAttribute > SID History: SID history of the created user (-)New Account > Account Name: Name of the created account (name of the added user)Attribute > Logon Time: Time at which the created user logged onSubject > Security ID: SID of the user who executed the tool (SID of the administrator)Attribute > New UAC Value: New UAC value for the created user (0x15)Attribute > Profile Path: Path to profile of the created userAttribute > User Principal Name: Principal name of the created user (-)Attribute > Allowed Delegation Destination: Delegation destination allowed for the created user (-)New Account > Security ID: SID of the created user (SID of the general user)Attribute > Primary Group ID: Primary group ID to which the created user belongs (513)Attribute > Display Name: Display name for the created userAttribute > SAM Account Name: SAM account name for the created user (added user name)New Account > Account Domain: Domain to which the created user belongs (Domain)Attribute > User Workstation: Workstation name for the created userSubject > Account Name: Name of the account that executed the tool (administrator)Subject > Account Domain: Domain to which the account belongs (domain)Additional Information > Privileges: Privilege information for the created user (-)Attribute > Home Directory: Home directory for the created userAttribute > Script Path: Script path for the created userAttribute > Home Drive: Home drive for the created userAttribute > User Parameter: Parameter for the created user
-- | -- | -- | --

**Comment by CalvinKrist** [comment]
Look for Event ID 4720
