### ISSUE TITLE
T1098 Account Manipulation

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#52]
https://attack.mitre.org/techniques/T1098/

Security | 4722 | User Account Management | A user account was enabled.Subject > Account Name: Name of the account that executed the tool (administrator)Target Account > Account Domain: Domain to which the enabled account belongs (Domain)Subject > Account Domain: Domain to which the account belongs (domain)Target Account > Account Name: Name of the enabled account (name of the added user)Subject > Security ID: SID of the user who executed the tool (SID of the administrator)Target Account > Security ID: SID of the enabled user (SID of the general user)
-- | -- | -- | --

Security | 4738 | User Account Management | A user account was changed.Changed Attribute > Home Drive: Changed home drive of the user (-)Target Account > Account Name: Changed name of the group (added user name)Changed Attribute > Display Name: Changed display name of the userChanged Attribute > Script Path: Changed path to the script of the user (-)Subject > Security ID: SID of the user who executed the tool (SID of the administrator)Changed Attribute > Allowed Delegation Destination: Changed delegation destination allowed for the user (-)Target Account > Account Domain: Changed domain to which the group belongs (Domain)Changed Attribute > User Workstation: Changed name of workstation of the user (-)Changed Attribute > SAM Account Name: Changed name of SAM account of the user (-)Target Account > Security ID: Changed SID of the group (SID of the general user)Changed Attribute > SID History: Changed history of SID of the user (-)Changed Attribute > Account Expiration Date: Changed date on which the user account expiresChanged Attribute > Password Last Set: Changed password of the user that was last set (execution time)Changed Attribute > User Principal Name: Changed principal name of the user (-)Changed Attribute > User Parameter: Changed parameter of the user (-)Changed Attribute > Primary Group ID: Changed primary group ID to which the user belongs (-)Changed Attribute > New UAC Value: New UAC value for the changed user (0x10)Changed Attribute > Old UAC Value: Old UAC value for the changed user (0x15)Changed Attribute > User Account Control: Changed account control for the user (the account is enabled)Changed Attribute > Logon Time: Changed time at which the user logged on (-)Subject > Account Name: Name of the account that executed the tool (administrator)Changed Attribute > Home Directory: Changed home directory of the user (-)Subject > Account Domain: Domain to which the account belongs (domain)Additional Information > Privileges: Changed privileges of the user (-)Changed Attribute > Profile Path: Changed path to the profile of the user (-)
-- | -- | -- | --

Security | 4724 | User Account Management | An attempt was made to reset an account password.Subject > Account Name: Name of the account that executed the tool (administrator)Target Account > Account Domain: Domain that the account for which an attempt was made to reset the password belongs to (Domain)Subject > Account Domain: Domain to which the account belongs (domain)Target Account > Account Name: Name of the account for which an attempt was made to reset the password (added user name)Subject > Security ID: SID of the user who executed the tool (SID of the administrator)Target Account > Security ID: SID of the user for which an attempt was made to reset the password (SID of the general user)
-- | -- | -- | --

**Comment by CalvinKrist** [comment]
Start with specific: enabling disabled accounts, upgrading account permissions

**Comment by ION28** [comment]
https://github.com/Neo23x0/sigma/blob/82cae6d63c9c2f6d3e86c57e11497d86279b9f95/rules/windows/builtin/win_user_added_to_local_administrators.yml adding user to login admin :)

**Comment by ION28** [comment]
Look for privileges like Tcb and SeDebug
