### ISSUE TITLE
Targeting Windows XP/Server 2003

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#60]
https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2019

**Comment by ION28** [comment]
Debug > BLUESPAWN Properties > Configuration Properties > General. Need to figure out what value Platform Toolset should take on (ie which versions of Windows to support). See the above link on how to support builds for back to 03

**Comment by jnmcd** [comment]
nope. XP support is a solid nope for me.

**Comment by ION28** [comment]
I expect in the next year or two, XP and 03 will really begin to phase out, they can only keep them around for so long. I mainly have this issue as a way to optionally produce a binary with just the basic hunts (ie whatever is supported back to XP/03). So it is a stripped down version. Envisioning only building this every several months, before a potential engagement
