### ISSUE TITLE
Fix bug in output for Registry Key identified

### ISSUE THREAD

**Issue by ION28** [ION28/BLUESPAWN#88]
**Reproduce:** 
```cmd
:: This branch contains new detections for subkeys of Run{Once, OnceEx}\ keys.
git checkout T1060-fix
Rebuild a new Release or Debug build

:: Add a registry key that will generate a detection via a CheckForSubkeys() Call
REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnceEx\0001\Depend /v 1 /d "C:\Path\AtomicRedTeam.dll"

:: Run BLUESPAWN
BLUESPAWN.exe --hunt -l Cursory
```

 **Description:** 
Based on my debugging, the error only appears to occur when there is a detection on this key. If I remove the Subkey `0001` and rerun BLUESPAWN, it does not crash. Once I rerun the `reg add` command from above though, it will crash again.
![image](https://user-images.githubusercontent.com/3931697/62815971-6a4e2600-baee-11e9-80bb-a3d2b90f856b.png)

**Comment by jnmcd** [comment]
Issue not reproducible through steps given
